### PR TITLE
Db add pdfs

### PR DESCRIPTION
**Pull request by damonbogich**

### CODE REVIEW

**Comment by ethulia** [comment]
I noticed that for most of the pngs that you made were of the cover page, rather than the "meaty" page with most of the parsed info on it. I think we should change the pngs to be the "main" page, even if it's not literally the first page. I think it would be more helpful, since more people I think would recognize it. 

For example, for the lemonade document, we shouldn't use the first page but rather page 2 of the PDF

**Comment by damonbogich** [comment]
@ethulia I replaced all of the cover page images with the more meaty pages

**Comment by damonbogich** [comment]
@ethulia just went through and updated the images again!

**Review by ethulia — APPROVED** [review]
@damonbogich Thank you! the screenshots looks good. If you can confirm that they have been anonymized or redacted then we're good to merge!

**Comment by damonbogich** [comment]
@ethulia can confirm pdfs/pngs are redacted or anonymized.  Did another pass on them and removed everything I thought was questionable.

**Pull request merged**
