### PR TITLE
add thumbnails for each PDF

### PR DESCRIPTION
**Pull request by samjespersen**
The front-end's Config Library section needs thumbnails of each PDF. Since we are already pulling the files from this repo to deliver them to the front-end, we decided that storing the thumbnails here as well is an acceptable solution. (That and relying on S3 has some issues with the workflow we're building.) This PR is to seed the config library with PNGs of the first page of every PDF. 

In the future, when there is a PR to main, a Github action (coming soon) will generate any missing PNGs from the commit and add them. The reviewer of the PR will need to inspect the PNG(s) since the algorithm still occasionally generates bad screenshot results (see https://github.com/sensible-hq/sensible/issues/1268). If the automated thumbnail isn't acceptable, then a screenshot will need to be manually uploaded in order for the config to be available on the front-end. This process will be added to the readme when ready to go live.

### CODE REVIEW

**Review by horacio-penya — APPROVED** [review]

**Comment by michaelwschultz** [comment]
This is great @samjespersen. My only issue is some of these images are pretty massive. I think we could easily scale them down a bit and they'll still look great. 

I've seen a 68% reduction in size 1.3MB -> 401 KB with no noticeable loss in quality in this file for instance.
acord_125_2014_12_sample (1)

Reducing these as much as possible could make a really big difference on the frontend.

There are a few ways we could automate this. Pushing these through a service like tinypng.com manually for now could be great. There is also tools we could use locally.

GUI - https://imageoptim.com/mac
CLI - https://pngquant.org/

**Comment by samjespersen** [comment]
@michaelwschultz Oh snap good point. I just checked and I ran the png generation at medium quality, which is obviously too big. I ran it again at low quality and the files are much more reasonable. Check it now!

**Review by damonbogich — APPROVED** [review]

**Comment by samjespersen** [comment]
@michaelwschultz ok all the pngs have been tinified via tinypng. everything so smol now :3

**Review by michaelwschultz — APPROVED** [review]
Looks great! Ship it!

**Review by angbonilla — APPROVED** [review]

**Review by ethulia — APPROVED** [review]

**Pull request merged**
