### PR TITLE
add new package policy dec pages doc type with chubb, cna, nationwide…

### PR DESCRIPTION
**Pull request by angbonilla**
…, and society configs.

- configs, samples, and screenshots added
- readme updated

### CODE REVIEW

**Comment by ethulia** [comment]
@angbonilla What did we end up deciding here -- was it that we'd start with putting just the Business Owner's Policy dec pages up since Package Policy was more custom? or was it the other way around?

**Comment by angbonilla** [comment]
> @angbonilla What did we end up deciding here -- was it that we'd start with putting just the Business Owner's Policy dec pages up since Package Policy was more custom? or was it the other way around?

We've decided on Business Owner's. I've made the appropriate name changes and replaced any package policy samples with bop samples.

**Comment by ethulia** [comment]
Looks good 🚢

**Review by ethulia — APPROVED** [review]
🚢

**Pull request merged**
